<?php
return array (
  'title' => '资质',
  'style' => '2',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '施工总承包序列资质标准',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3365,3388,3389,3390,3391,3366,3392,3393,3394,3396,3378,3397,3398,3399,3400,3379,3380,3381,3382,3383,3384,3385,3386,3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '设计与施工一体化资质',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3401,3405,3406,3402,3407,3408,3403,3409,3410,3404,3411,3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '专业承包序列资质标准',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3413,3449,3450,3451,3414,3452,3453,3454,3415,3455,3456,3457,3416,3458,3459,3460,3417,3461,3462,3463,3418,3464,3465,3466,3419,3467,3468,3469,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3447,3448',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '建筑工程',
      'style' => '0',
      'parentid' => '3361',
      'child' => '1',
      'arrchildid' => '3365,3388,3389,3390,3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '公路工程',
      'style' => '0',
      'parentid' => '3361',
      'child' => '1',
      'arrchildid' => '3366,3392,3393,3394,3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '施工劳务企业资质标准',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3367,3470,3472,3471,3473',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '安防工程企业资质',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3368',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '承装（修、试）电力施工许可证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3369',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '城市园林绿化企业资质标准',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '工程监理资质标准',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '事务所资质标准',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '工程勘察资质标准',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '工程设计综合资质',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '工程设计行业资质',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '工程设计专业资质',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '工程设计专项资质',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '铁路工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '1',
      'arrchildid' => '3378,3397,3398,3399,3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '港口与航道工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '水利水电工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '电力工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '矿山工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '冶金工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '通信工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '石油化工工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '机电工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '市政公用工程',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '一级',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '二级',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '三级',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '特级',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '一级',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '二级',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '三级',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '特级',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '一级',
      'style' => '',
      'parentid' => '3378',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '二级',
      'style' => '',
      'parentid' => '3378',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '三级',
      'style' => '',
      'parentid' => '3378',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '特级',
      'style' => '',
      'parentid' => '3378',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '建筑智能化工程设计与施工资质',
      'style' => '',
      'parentid' => '3362',
      'child' => '1',
      'arrchildid' => '3401,3405,3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '消防设施工程设计与施工资质',
      'style' => '',
      'parentid' => '3362',
      'child' => '1',
      'arrchildid' => '3402,3407,3408',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '建筑装饰装修工程设计与施工资质',
      'style' => '',
      'parentid' => '3362',
      'child' => '1',
      'arrchildid' => '3403,3409,3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '建筑幕墙工程设计与施工资质',
      'style' => '',
      'parentid' => '3362',
      'child' => '1',
      'arrchildid' => '3404,3411,3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '一级',
      'style' => '',
      'parentid' => '3401',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '二级',
      'style' => '',
      'parentid' => '3401',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '一级',
      'style' => '',
      'parentid' => '3402',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '二级',
      'style' => '',
      'parentid' => '3402',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '一级',
      'style' => '',
      'parentid' => '3403',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '二级',
      'style' => '',
      'parentid' => '3403',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '一级',
      'style' => '',
      'parentid' => '3404',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '二级',
      'style' => '',
      'parentid' => '3404',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '地基基础工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3413,3449,3450,3451',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '起重设备安装工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3414,3452,3453,3454',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '预拌混凝土工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3415,3455,3456,3457',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '电子与智能化工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3416,3458,3459,3460',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '消防设施工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3417,3461,3462,3463',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '防水防腐保温工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3418,3464,3465,3466',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '桥梁工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '1',
      'arrchildid' => '3419,3467,3468,3469',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '隧道工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '钢结构工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '模板脚手架',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '建筑装修装饰工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '建筑机电安装工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '建筑幕墙工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '古建筑工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '城市及道路照明工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '公路路面工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '公路路基工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '公路交通工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '铁路电务工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '铁路辅轨架梁工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '铁路电气化工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '机场场道工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '民航空管工程及机场弱电系统工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '机场目视助航工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '港口与海岸工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '航道工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '通航建筑物工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '港航设备安装及水上交管工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '水工金属结构制作与安装工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '水利水电机电安装工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3442',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '河湖整治工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '输变电工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '核工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3446 => 
    array (
      'linkageid' => '3446',
      'name' => '海洋石油工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3446',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3447 => 
    array (
      'linkageid' => '3447',
      'name' => '环保工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3447',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3448 => 
    array (
      'linkageid' => '3448',
      'name' => '特种工程',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3448',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3449 => 
    array (
      'linkageid' => '3449',
      'name' => '一级',
      'style' => '',
      'parentid' => '3413',
      'child' => '0',
      'arrchildid' => '3449',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3450 => 
    array (
      'linkageid' => '3450',
      'name' => '二级',
      'style' => '',
      'parentid' => '3413',
      'child' => '0',
      'arrchildid' => '3450',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3451 => 
    array (
      'linkageid' => '3451',
      'name' => '三级',
      'style' => '',
      'parentid' => '3413',
      'child' => '0',
      'arrchildid' => '3451',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3452 => 
    array (
      'linkageid' => '3452',
      'name' => '一级',
      'style' => '',
      'parentid' => '3414',
      'child' => '0',
      'arrchildid' => '3452',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3453 => 
    array (
      'linkageid' => '3453',
      'name' => '二级',
      'style' => '',
      'parentid' => '3414',
      'child' => '0',
      'arrchildid' => '3453',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3454 => 
    array (
      'linkageid' => '3454',
      'name' => '三级',
      'style' => '',
      'parentid' => '3414',
      'child' => '0',
      'arrchildid' => '3454',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3455 => 
    array (
      'linkageid' => '3455',
      'name' => '一级',
      'style' => '',
      'parentid' => '3415',
      'child' => '0',
      'arrchildid' => '3455',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3456 => 
    array (
      'linkageid' => '3456',
      'name' => '二级',
      'style' => '',
      'parentid' => '3415',
      'child' => '0',
      'arrchildid' => '3456',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3457 => 
    array (
      'linkageid' => '3457',
      'name' => '三级',
      'style' => '',
      'parentid' => '3415',
      'child' => '0',
      'arrchildid' => '3457',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3458 => 
    array (
      'linkageid' => '3458',
      'name' => '一级',
      'style' => '',
      'parentid' => '3416',
      'child' => '0',
      'arrchildid' => '3458',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3459 => 
    array (
      'linkageid' => '3459',
      'name' => '二级',
      'style' => '',
      'parentid' => '3416',
      'child' => '0',
      'arrchildid' => '3459',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3460 => 
    array (
      'linkageid' => '3460',
      'name' => '三级',
      'style' => '',
      'parentid' => '3416',
      'child' => '0',
      'arrchildid' => '3460',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3461 => 
    array (
      'linkageid' => '3461',
      'name' => '一级',
      'style' => '',
      'parentid' => '3417',
      'child' => '0',
      'arrchildid' => '3461',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3462 => 
    array (
      'linkageid' => '3462',
      'name' => '二级',
      'style' => '',
      'parentid' => '3417',
      'child' => '0',
      'arrchildid' => '3462',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3463 => 
    array (
      'linkageid' => '3463',
      'name' => '三级',
      'style' => '',
      'parentid' => '3417',
      'child' => '0',
      'arrchildid' => '3463',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3464 => 
    array (
      'linkageid' => '3464',
      'name' => '一级',
      'style' => '',
      'parentid' => '3418',
      'child' => '0',
      'arrchildid' => '3464',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3465 => 
    array (
      'linkageid' => '3465',
      'name' => '二级',
      'style' => '',
      'parentid' => '3418',
      'child' => '0',
      'arrchildid' => '3465',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3466 => 
    array (
      'linkageid' => '3466',
      'name' => '三级',
      'style' => '',
      'parentid' => '3418',
      'child' => '0',
      'arrchildid' => '3466',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3467 => 
    array (
      'linkageid' => '3467',
      'name' => '一级',
      'style' => '',
      'parentid' => '3419',
      'child' => '0',
      'arrchildid' => '3467',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3468 => 
    array (
      'linkageid' => '3468',
      'name' => '二级',
      'style' => '',
      'parentid' => '3419',
      'child' => '0',
      'arrchildid' => '3468',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3469 => 
    array (
      'linkageid' => '3469',
      'name' => '三级',
      'style' => '',
      'parentid' => '3419',
      'child' => '0',
      'arrchildid' => '3469',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3470 => 
    array (
      'linkageid' => '3470',
      'name' => '二级测试',
      'style' => '',
      'parentid' => '3367',
      'child' => '1',
      'arrchildid' => '3470,3472',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3471 => 
    array (
      'linkageid' => '3471',
      'name' => '二恶',
      'style' => '',
      'parentid' => '3367',
      'child' => '1',
      'arrchildid' => '3471,3473',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3472 => 
    array (
      'linkageid' => '3472',
      'name' => 'ABC',
      'style' => '',
      'parentid' => '3470',
      'child' => '0',
      'arrchildid' => '3472',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3473 => 
    array (
      'linkageid' => '3473',
      'name' => '哈哈哈',
      'style' => '',
      'parentid' => '3471',
      'child' => '0',
      'arrchildid' => '3473',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>