<?php
return array (
  1 => 
  array (
    'catid' => '1',
    'parentid' => '0',
    'catname' => '建筑资质服务',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=1&siteid=1',
    'status' => '1',
  ),
  2 => 
  array (
    'catid' => '2',
    'parentid' => '0',
    'catname' => '安全生产许可证',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=2&siteid=1',
    'status' => '1',
  ),
  4 => 
  array (
    'catid' => '4',
    'parentid' => '0',
    'catname' => '成功案例',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=4&siteid=1',
    'status' => '1',
  ),
  5 => 
  array (
    'catid' => '5',
    'parentid' => '0',
    'catname' => '新闻动态',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=5&siteid=1',
    'status' => '1',
  ),
  6 => 
  array (
    'catid' => '6',
    'parentid' => '0',
    'catname' => '关于我们',
    'siteid' => '1',
    'listorder' => '6',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=6&siteid=1',
    'status' => '1',
  ),
  8 => 
  array (
    'catid' => '8',
    'parentid' => '7',
    'catname' => '首页banner',
    'siteid' => '1',
    'listorder' => '8',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=8&siteid=1',
    'status' => '1',
  ),
  9 => 
  array (
    'catid' => '9',
    'parentid' => '1',
    'catname' => '建筑总承包',
    'siteid' => '1',
    'listorder' => '9',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=9&siteid=1',
    'status' => '1',
  ),
  10 => 
  array (
    'catid' => '10',
    'parentid' => '1',
    'catname' => '建筑专业承包',
    'siteid' => '1',
    'listorder' => '10',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=10&siteid=1',
    'status' => '1',
  ),
  11 => 
  array (
    'catid' => '11',
    'parentid' => '1',
    'catname' => '建筑劳务分包',
    'siteid' => '1',
    'listorder' => '11',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=11&siteid=1',
    'status' => '1',
  ),
  12 => 
  array (
    'catid' => '12',
    'parentid' => '2',
    'catname' => '安证新办',
    'siteid' => '1',
    'listorder' => '12',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=12&siteid=1',
    'status' => '1',
  ),
  13 => 
  array (
    'catid' => '13',
    'parentid' => '2',
    'catname' => '安证延期',
    'siteid' => '1',
    'listorder' => '13',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=13&siteid=1',
    'status' => '1',
  ),
  14 => 
  array (
    'catid' => '14',
    'parentid' => '2',
    'catname' => '安证过期办理',
    'siteid' => '1',
    'listorder' => '14',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=14&siteid=1',
    'status' => '1',
  ),
  17 => 
  array (
    'catid' => '17',
    'parentid' => '5',
    'catname' => '新闻动态',
    'siteid' => '1',
    'listorder' => '17',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=17&siteid=1',
    'status' => '1',
  ),
  18 => 
  array (
    'catid' => '18',
    'parentid' => '5',
    'catname' => '政策法规',
    'siteid' => '1',
    'listorder' => '18',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=18&siteid=1',
    'status' => '1',
  ),
  19 => 
  array (
    'catid' => '19',
    'parentid' => '7',
    'catname' => '建筑资质服务banner',
    'siteid' => '1',
    'listorder' => '19',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=19&siteid=1',
    'status' => '1',
  ),
  20 => 
  array (
    'catid' => '20',
    'parentid' => '7',
    'catname' => '安全生产许可banner',
    'siteid' => '1',
    'listorder' => '20',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=20&siteid=1',
    'status' => '1',
  ),
  21 => 
  array (
    'catid' => '21',
    'parentid' => '3',
    'catname' => '人才证书查询',
    'siteid' => '1',
    'listorder' => '21',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=21&siteid=1',
    'status' => '1',
  ),
  22 => 
  array (
    'catid' => '22',
    'parentid' => '3',
    'catname' => '企业资质查询',
    'siteid' => '1',
    'listorder' => '22',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=22&siteid=1',
    'status' => '1',
  ),
  23 => 
  array (
    'catid' => '23',
    'parentid' => '3',
    'catname' => '备案业绩查询',
    'siteid' => '1',
    'listorder' => '23',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=23&siteid=1',
    'status' => '1',
  ),
  24 => 
  array (
    'catid' => '24',
    'parentid' => '7',
    'catname' => '查询工具banner',
    'siteid' => '1',
    'listorder' => '24',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=24&siteid=1',
    'status' => '1',
  ),
  25 => 
  array (
    'catid' => '25',
    'parentid' => '7',
    'catname' => '成功案例banner',
    'siteid' => '1',
    'listorder' => '25',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=25&siteid=1',
    'status' => '1',
  ),
  26 => 
  array (
    'catid' => '26',
    'parentid' => '7',
    'catname' => '新闻动态banner',
    'siteid' => '1',
    'listorder' => '26',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=26&siteid=1',
    'status' => '1',
  ),
  27 => 
  array (
    'catid' => '27',
    'parentid' => '6',
    'catname' => '公司介绍',
    'siteid' => '1',
    'listorder' => '27',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=27&siteid=1',
    'status' => '1',
  ),
  28 => 
  array (
    'catid' => '28',
    'parentid' => '6',
    'catname' => '联系我们',
    'siteid' => '1',
    'listorder' => '28',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=28&siteid=1',
    'status' => '1',
  ),
  29 => 
  array (
    'catid' => '29',
    'parentid' => '7',
    'catname' => '关于我们banner',
    'siteid' => '1',
    'listorder' => '29',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=29&siteid=1',
    'status' => '1',
  ),
  31 => 
  array (
    'catid' => '31',
    'parentid' => '7',
    'catname' => '手机banner',
    'siteid' => '1',
    'listorder' => '31',
    'type' => '0',
    'url' => '/index.php?m=mobile&a=lists&catid=31&siteid=1',
    'status' => '1',
  ),
);
?>